In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib notebook

In [2]:
finalAllCityTempsDf=pd.DataFrame([])
cityList=['Bernalillo_County','Clark_County','Cook_County','Dallas_County','Davidson_County','Denver_County','Fulton_County','Hennepin_County','Jackson_County','King_County','Los_Angeles_County','Maricopa_County','Marion_County','Mecklenburg_County','Miami_Dade_County','New_York_County','Philadelphia_County','San_Francisco_County','Suffolk_County','Wayne_County']

In [3]:
for city in cityList:    
    #Import CSV file
    csvCity=f"{city}.csv"
    cityDf=pd.read_csv(csvCity)

    #Selected columns we want in our dataframe

    newColumns=['DATE', 'HourlyDryBulbTemperature']

    #Create new data frame based on given columns list

    shortCityDf=cityDf[newColumns]

    #Drop rows with null values. We do not fill values with zeros here as they might be mistaken for temperatures in further analysis

    shortCityDf=shortCityDf.dropna(axis=0)

    #Get only those rows from the month of January, create new data frame for just January

    CityDf2014=shortCityDf.loc[shortCityDf['DATE'].str.contains('2014-01'), newColumns]

    #Convert temperatures into floats. Non-numerical values will be converted to NaN using 'coerce'
    CityDf2014['Hourly_Dry_Bulb_Temperature']=pd.to_numeric(CityDf2014['HourlyDryBulbTemperature'], errors='coerce')

    #Drop the na values

    CityDf2014=CityDf2014.dropna(axis=0)

    countyName=csvCity.replace('.csv', '')

    CityDf2014['County_Name']=countyName

    CityDf2014=CityDf2014.rename(columns={'DATE':'Date'})

    CityDf2014=CityDf2014[['County_Name', 'Date', 'Hourly_Dry_Bulb_Temperature']]

    finalAllCityTempsDf=finalAllCityTempsDf.append(CityDf2014)

finalAllCityTempsDf

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (42,43,56) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,28,29,30,32,35,36,43,49,53,56,58,59,63,71,95,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (41,42,43,51,55,56) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (41,42,43,49,51) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (41,42,43,49,52,73) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,19,25,26,27,28,29,30,31,33,41,42,48,49,51,52,53,55,56,58,59,71,72,73,75,76,89,95,96,97,98,99,100,101,102,103,104,105,106,107,110) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (19,25,26,27,28,29,34,35,36,58,59,61,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,19,25,26,27,28,30,31,41,42,43,49,51,52,58,59,60,69,71,72,88,95,96,97,98,99,100,101,102,103,104,105,106,107,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,19,25,26,27,28,35,42,43,56,59,95,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (42,43,48,53,58,60,63) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,28,29,30,32,35,36,43,49,53,56,58,59,63,71,95,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (41,56) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,19,25,26,27,28,29,35,36,41,42,43,49,51,55,56,58,59,60,63,95,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (19,25,26,27,29,33,34,41,42,43,49,51,56,69,71,73,75,76,88,89) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (42,43) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (33,41,42,49,51,89) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,19,25,26,27,28,29,41,51,56,58,59,60,77,82,95,114,117,118,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (42,43) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (75,89) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

            County_Name                 Date  Hourly_Dry_Bulb_Temperature
0     Bernalillo_County  2014-01-01T00:15:00                         22.0
1     Bernalillo_County  2014-01-01T00:35:00                         23.0
2     Bernalillo_County  2014-01-01T00:55:00                         21.0
3     Bernalillo_County  2014-01-01T01:15:00                         22.0
4     Bernalillo_County  2014-01-01T01:35:00                         21.0
...                 ...                  ...                          ...
1415       Wayne_County  2014-01-31T20:53:00                         28.0
1416       Wayne_County  2014-01-31T21:53:00                         27.0
1417       Wayne_County  2014-01-31T22:00:00                         27.0
1418       Wayne_County  2014-01-31T22:53:00                         28.0
1419       Wayne_County  2014-01-31T23:53:00                         28.0

[22867 rows x 3 columns]

In [5]:
finalAllCityTempsDf.to_csv('2014_All_Temps.csv', index=False, header=True)