In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib notebook

In [5]:
finalCityDf=pd.DataFrame([])
cityList=['Bernalillo_County','Clark_County','Cook_County','Dallas_County','Davidson_County','Denver_County','Fulton_County','Hennepin_County','Jackson_County','King_County','Los_Angeles_County','Maricopa_County','Marion_County','Mecklenburg_County','Miami_Dade_County','New_York_County','Philadelphia_County','San_Francisco_County','Suffolk_County','Wayne_County']

In [6]:
for city in cityList:    
    #Import CSV file
    csvCity=f"{city}.csv"
    cityDf=pd.read_csv(csvCity)

    #Selected columns we want in our dataframe

    newColumns=['DATE', 'HourlyDryBulbTemperature']

    #Create new data frame based on given columns list

    shortCityDf=cityDf[newColumns]

    #Drop rows with null values. We do not fill values with zeros here as they might be mistaken for temperatures in further analysis

    shortCityDf=shortCityDf.dropna(axis=0)

    #Get only those rows from the month of January, create new data frame for just January

    CityDf2014=shortCityDf.loc[shortCityDf['DATE'].str.contains('2014-01'), newColumns]

    #Convert temperatures into floats. Non-numerical values will be converted to NaN using 'coerce'
    CityDf2014['HourlyDryBulbTemperature']=pd.to_numeric(CityDf2014['HourlyDryBulbTemperature'], errors='coerce')
    
    #Drop the na values
    
    CityDf2014=CityDf2014.dropna(axis=0)

    #Get median temperature of the month

    monthlyMedian=CityDf2014['HourlyDryBulbTemperature'].median()

    #Calculate the months minimum temperature

    monthlyMin=CityDf2014['HourlyDryBulbTemperature'].min()

    #Calculate the months maximum temperature

    monthlyMax=CityDf2014['HourlyDryBulbTemperature'].max()

    #Get mean temperature and round to one decimal place

    monthlyMean=round((CityDf2014['HourlyDryBulbTemperature'].mean()),1)

    #Get county name from csv title

    countyName=csvCity.replace('.csv', '')

    #Split date based on '-'. Get year from list of split values. 

    year=(CityDf2014['DATE'].str.split(pat='-', n=0))[0][0]

    #Create a data frame by defining column names and passing in variables calculated from original dataframe

    CityDf2014Summary=[{'County':countyName,'Year':year, 'Jan_Min_Temp':monthlyMin, 'Jan_Max_Temp':monthlyMax, 'Jan_Mean_Temp':monthlyMean, 'Jan_Median_Temp':monthlyMedian}]
    
    CityDf2014SummaryDf=pd.DataFrame(CityDf2014Summary)

    #Set county name as the index

    CityDf2014SummaryDf=CityDf2014SummaryDf.set_index('County')
    
    finalCityDf=finalCityDf.append(CityDf2014SummaryDf)
finalCityDf

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (42,43,56) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,28,29,30,32,35,36,43,49,53,56,58,59,63,71,95,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (41,42,43,51,55,56) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (41,42,43,49,51) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (41,42,43,49,52,73) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,19,25,26,27,28,29,30,31,33,41,42,48,49,51,52,53,55,56,58,59,71,72,73,75,76,89,95,96,97,98,99,100,101,102,103,104,105,106,107,110) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (19,25,26,27,28,29,34,35,36,58,59,61,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,19,25,26,27,28,30,31,41,42,43,49,51,52,58,59,60,69,71,72,88,95,96,97,98,99,100,101,102,103,104,105,106,107,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,19,25,26,27,28,35,42,43,56,59,95,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (42,43,48,53,58,60,63) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,28,29,30,32,35,36,43,49,53,56,58,59,63,71,95,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (41,56) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,19,25,26,27,28,29,35,36,41,42,43,49,51,55,56,58,59,60,63,95,114,117,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (19,25,26,27,29,33,34,41,42,43,49,51,56,69,71,73,75,76,88,89) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (42,43) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (33,41,42,49,51,89) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (3,19,25,26,27,28,29,41,51,56,58,59,60,77,82,95,114,117,118,119) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (42,43) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (75,89) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Year,Jan_Min_Temp,Jan_Max_Temp,Jan_Mean_Temp,Jan_Median_Temp
County,,,,,
Bernalillo_County,2014,8.0,64.0,30.8,29.0
Clark_County,2014,48.0,79.0,61.5,62.0
Cook_County,2014,-15.0,47.0,16.6,19.0
Dallas_County,2014,15.0,74.0,44.8,45.0
Davidson_County,2014,1.0,63.0,33.2,35.0
Denver_County,2014,-8.0,64.0,29.5,30.0
Fulton_County,2014,6.0,67.0,36.7,37.0
Hennepin_County,2014,-22.0,39.0,9.6,9.0
Jackson_County,2014,-8.0,63.0,26.7,28.0
King_County,2014,28.0,59.0,41.8,43.0
Los_Angeles_County,2014,48.0,79.0,61.5,62.0
Maricopa_County,2014,32.0,77.0,53.5,54.0
Marion_County,2014,-14.0,50.0,20.3,21.5
Mecklenburg_County,2014,7.0,64.0,36.9,38.0
Miami_Dade_County,2014,41.0,83.0,66.9,68.0
New_York_County,2014,4.0,58.0,30.6,31.0
Philadelphia_County,2014,4.0,64.0,30.1,28.0
San_Francisco_County,2014,51.0,62.0,56.7,57.0
Suffolk_County,2014,1.0,58.0,28.3,28.0
Wayne_County,2014,-14.0,45.0,17.7,17.0

In [7]:
finalCityDf.to_csv('2014_Weather_Summary.csv', index=True, header=True)